name: $(Date:yyyyMMdd).$(BuildID)

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04

  strategy:
    matrix:
      GCC:
        CC: gcc
        CXX: g++
      Clang:
        CC: clang
        CXX: clang++

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: x64

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: Install Meson

  - script: sudo apt-get update && sudo apt-get -q install ninja-build
    displayName: Install Ninja

  - script: meson setup build
    displayName: Generate

  - script: |
      cd build
      ninja
    displayName: Build

- job: Windows
  pool:
    vmImage: vs2017-win2016

  strategy:
    matrix:
      x86:
        target_arch: x86
      x64:
        target_arch: amd64

  steps:
  - task: BatchScript@1
    inputs:
      filename: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat
      arguments: -no_logo -arch=$(target_arch)
      modifyEnvironment: true
    displayName: Setup Environment Variables

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: x64

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: Install Meson

  - script: choco install ninja --no-progress
    displayName: Install Ninja

  - script: meson setup build
    displayName: Generate

  - script: |
      cd build
      ninja
    displayName: Build
